<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit141456ad0a77e6bbe7dcca92f68c462d
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Recca0120\QuickOrder\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Recca0120\QuickOrder\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit141456ad0a77e6bbe7dcca92f68c462d', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Recca0120\QuickOrder\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit141456ad0a77e6bbe7dcca92f68c462d', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Recca0120\QuickOrder\Vendor\Composer\Autoload\ComposerStaticInit141456ad0a77e6bbe7dcca92f68c462d::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
