<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Recca0120\\QuickOrder\\Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Recca0120\\QuickOrder\\Admin' => $baseDir . '/src/Admin.php',
    'Recca0120\\QuickOrder\\Config' => $baseDir . '/src/Config.php',
    'Recca0120\\QuickOrder\\Middleware\\SyncOrderMiddleware' => $baseDir . '/src/Middleware/SyncOrderMiddleware.php',
    'Recca0120\\QuickOrder\\OrderForm' => $baseDir . '/src/OrderForm.php',
    'Recca0120\\QuickOrder\\OrderService' => $baseDir . '/src/OrderService.php',
    'Recca0120\\QuickOrder\\RestApi' => $baseDir . '/src/RestApi.php',
    'Recca0120\\QuickOrder\\Shortcode' => $baseDir . '/src/Shortcode.php',
);
