<?php

// autoload_static.php @generated by Composer

namespace Recca0120\QuickOrder\Vendor\Composer\Autoload;

class ComposerStaticInit141456ad0a77e6bbe7dcca92f68c462d
{
    public static $prefixLengthsPsr4 = array (
        'R' =>
        array (
            'Recca0120\\QuickOrder\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Recca0120\\QuickOrder\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Recca0120\\QuickOrder\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Recca0120\\QuickOrder\\Admin' => __DIR__ . '/../..' . '/src/Admin.php',
        'Recca0120\\QuickOrder\\Config' => __DIR__ . '/../..' . '/src/Config.php',
        'Recca0120\\QuickOrder\\Middleware\\SyncOrderMiddleware' => __DIR__ . '/../..' . '/src/Middleware/SyncOrderMiddleware.php',
        'Recca0120\\QuickOrder\\OrderForm' => __DIR__ . '/../..' . '/src/OrderForm.php',
        'Recca0120\\QuickOrder\\OrderService' => __DIR__ . '/../..' . '/src/OrderService.php',
        'Recca0120\\QuickOrder\\RestApi' => __DIR__ . '/../..' . '/src/RestApi.php',
        'Recca0120\\QuickOrder\\Shortcode' => __DIR__ . '/../..' . '/src/Shortcode.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit141456ad0a77e6bbe7dcca92f68c462d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit141456ad0a77e6bbe7dcca92f68c462d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit141456ad0a77e6bbe7dcca92f68c462d::$classMap;

        }, null, ClassLoader::class);
    }
}
